name: Workflow Reproducer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  api_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick
          coverage: pcov
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: |
          php bin/phpunit
